// <auto-generated />
namespace WebLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AltUserDrop_adr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AltUserDrop_adr));
        
        string IMigrationMetadata.Id
        {
            get { return "201912150401266_Alt-User-Drop_adr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
